apiVersion: platform.local.lab/v1alpha1
kind: SecretMirror
metadata:
  labels:
    app.kubernetes.io/name: secret-mirror-controller
    app.kubernetes.io/managed-by: kustomize
  name: secretmirror-sample
spec:
  # TODO(user): Add fields here
